git://github.com/payne/22May2012Talk.git
git://github.com/payne/24May2012Talk.git
git://github.com/payne/26Aug2013Talk.git
git://github.com/payne/Blog.git
git://github.com/payne/effective-django.git
git://github.com/payne/EmfStore-Test.git
git://github.com/payne/enumerous.git
git://github.com/payne/flickr-fuse.git
git://github.com/payne/git-encrypt.git
git://github.com/payne/github-api.git
git://github.com/payne/github_cleaner.git
git://github.com/payne/groovy-demo.git
git://github.com/payne/hackomaha-council-agendas.git
git://github.com/payne/handbook.git
git://github.com/payne/hello-java-spring-force_dot_com.git
git://github.com/payne/hellodjango.git
git://github.com/payne/html5demos.git
git://github.com/payne/ideas.git
git://github.com/payne/initializr-code-school.git
git://github.com/payne/inverted-index.git
git://github.com/payne/iphone-html5-offline-app-demo.git
git://github.com/payne/JasmineCoffee.git
git://github.com/payne/java-koans.git
git://github.com/payne/java-koans-1.git
git://github.com/payne/JavaScript-Koans.git
git://github.com/payne/JBehaveWithGradle.git
git://github.com/payne/JenaJung.git
git://github.com/payne/jetty-embedded-spring-mvc-noxml.git
git://github.com/payne/jqfundamentals.git
git://github.com/payne/jquery-tiny-pubsub.git
git://github.com/payne/MattPayneOrg-Junk-Drawer.git
git://github.com/payne/meetwithapproval.git
git://github.com/payne/mgpTicketee.git
git://github.com/payne/MMI.git
git://github.com/payne/MongoDB_Koans.git
git://github.com/payne/OJUG-February-2012-Restlet.git
git://github.com/payne/omg-code.git
git://github.com/payne/payne.github.com.git
git://github.com/payne/Projects.git
git://github.com/payne/rails_testing.git
git://github.com/payne/RegularExpressionTester.git
git://github.com/payne/ResponsiveSlides.js.git
git://github.com/payne/RFZ2-ZombieTweets.git
git://github.com/payne/rubyrefresher.git
git://github.com/payne/ruby_koans.git
git://github.com/payne/sexy-bash-prompt.git
git://github.com/payne/SimpleTimeCard.git
git://github.com/payne/springmvc-hibernate-template.git
git://github.com/payne/starlight.git
git://github.com/payne/StarLogs.git
git://github.com/payne/swinger.git
git://github.com/payne/techradar.git
git://github.com/payne/tycho-demo.git
git://github.com/payne/vim-gtd.git
